version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/local-initdb.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: